######################################################################
# Automatically generated by qmake (2.01a) ??? ??? 28 14:01:08 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
